import type { NextPage } from "next";
import Head from "next/head";
import Container from "@mui/material/Container";
import Hero from "../components/Hero";
import { APIContextProvider } from "../context";
import CardStudentTotal from "../components/CardStudentTotal";
import CardCuotasPagadas from "../components/CardCuotasPagadas";
import CardCuotasPendientes from "../components/CardCuotasPendientes";
import { Formik } from "formik";
import { Button } from "@mui/material";

const Home: NextPage = () => {
  return (
    <APIContextProvider>
      <Formik initialValues={{ checked: [] }} onSubmit={(values) => console.log("test")}>
        {({ handleSubmit, values }) => (
          <>
            <Head>
              <title>Colegio Brillamont</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Container maxWidth="md">
              <CardStudentTotal />
              <CardCuotasPagadas />
              <CardCuotasPendientes type="pendientes" />
              <CardCuotasPendientes type="futuras" />
              {values.checked.length > 0 && (
                <Container sx={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <Button
                    type="submit"
                    variant="contained"
                    sx={{ maxWidth: "320px", maxHeight: "50px", minWidth: "320px", minHeight: "50px" }}
                    onClick={() => console.log(values.checked.length)}
                  >
                    IR A PAGAR
                  </Button>
                </Container>
              )}
            </Container>
          </>
        )}
      </Formik>
    </APIContextProvider>
  );
};

export default Home;
